name       : libvisio
version    : 0.1.6
release    : 7
source     :
    - https://dev-www.libreoffice.org/src/libvisio/libvisio-0.1.6.tar.xz : fe1002d3671d53c09bc65e47ec948ec7b67e6fb112ed1cd10966e211a8bb50f9
license    : MPL-2.0
component  : programming
summary    : Library and a set of tools for reading and converting MS Visio diagrams
description: |
    Libvisio is a library and a set of tools for reading and converting MS Visio diagrams.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(librevenge-0.0)
    - gperf
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
