name       : libvisio
version    : 0.1.5
release    : 1
source     :
    - http://dev-www.libreoffice.org/src/libvisio/libvisio-0.1.5.tar.xz : 430a067903660bb1b97daf4b045e408a1bb75ca45e615cf05fb1a4da65fc5a8c
license    : MPL-2.0
component  : programming
summary    : Library and a set of tools for reading and converting MS Visio diagrams
description: |
    Libvisio is a library and a set of tools for reading and converting MS Visio diagrams.
builddeps  :
    - pkgconfig(cppunit)
    - pkgconfig(icu-i18n)
    - pkgconfig(librevenge-0.0)
    - gperf
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
